/* Copyright 2007-2011 MTA SZTAKI LPDS, Budapest

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package hu.sztaki.lpds.pgportal.services.asm.beans;

/**
 * Class to store details (output logs/statuses) for a job instance
 * @author akos
 * @version 3.3
 */
public class ASMJobInstanceBean {

    private String id;


    private String status;
    private String outputText;
    private String errorText;
    private String usedResource;
    private String logbookText;
    /**
     * Gets the id of the job instance
     * @return id
     */
    public String getId() {
        return id;
    }
/**
 * Setter method
 * @param id
 */
    public void setId(String id) {
        this.id = id;
    }
    public String getUsedResource() {
        return usedResource;
    }
/**
 * Setter method
 * @param usedResource
 */
    public void setUsedResource(String usedResource) {
        this.usedResource = usedResource;
    }
    
/**
 * Constructor
 * @param id - id of the job instance
 * @param status - status of the job instance
 * @param usedResource - resource, where the job instance was submitted
 * @param outputText - stdout.log
 * @param errorText - stderr.log
 * @param logbookText - gridnfo.log
 */
    public ASMJobInstanceBean(String id, String status,String usedResource, String outputText, String errorText, String logbookText) {
        this.id = id;
        this.status = status;
        this.usedResource = usedResource;
        this.outputText = outputText;
        this.errorText = errorText;
        this.logbookText = logbookText;
    }
/**
 * Default constructor
 */
    public ASMJobInstanceBean() {
    }
/**
 * Gets the std. error text
 * @return std.err
 */
    public String getErrorText() {
        return errorText;
    }

    /**
     * Setter method
     * @param errorText
     */
    public void setErrorText(String errorText) {
        this.errorText = errorText;
    }
/**
 * Gets logging information generated by guse system (wrapper script)
 * @return
 */
    public String getLogbookText() {
        return logbookText;
    }
/**
 * Setter method
 * @param logbookText
 */
    public void setLogbookText(String logbookText) {
        this.logbookText = logbookText;
    }

/**
 * Gets the standard output text generated by the job instance
 * @return std.out
 */
    public String getOutputText() {
        return outputText;
    }
/**
 * Setter method
 * @param outputText
 */
    public void setOutputText(String outputText) {
        this.outputText = outputText;
    }
/**
 * Gets the status of the job instance
 * @return
 */
    public String getStatus() {
        return status;
    }
/**
 * Setter method
 * @param status
 */
    public void setStatus(String status) {
        this.status = status;
    }
}
