//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.27 at 11:01:57 AM CEST 
//


package de.mosgrid.msml.jaxb.bindings;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for atomType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="atomType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}residueName"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}atomName"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}chainName"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}dictRef"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}formalCharge"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}atomVelocities"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}count"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}ref"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}altLoc"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}convention"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}residueNumber"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}title"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}elementType"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}id"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}customId"/>
 *       &lt;attribute name="x2" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="x3" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="y2" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="y3" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="z3" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "atomType")
public class AtomType {

    @XmlAttribute
    protected Float x2;
    @XmlAttribute
    protected Float x3;
    @XmlAttribute
    protected Float y2;
    @XmlAttribute
    protected Float y3;
    @XmlAttribute
    protected Float z3;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String residueName;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String atomName;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String chainName;
    @XmlAttribute
    protected String dictRef;
    @XmlAttribute
    protected BigInteger formalCharge;
    @XmlAttribute(name = "vX", namespace = "http://www.xml-cml.org/schema/cmlx")
    protected Double vx;
    @XmlAttribute(name = "vY", namespace = "http://www.xml-cml.org/schema/cmlx")
    protected Double vy;
    @XmlAttribute(name = "vZ", namespace = "http://www.xml-cml.org/schema/cmlx")
    protected Double vz;
    @XmlAttribute
    protected Double count;
    @XmlAttribute
    protected String ref;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String altLoc;
    @XmlAttribute
    protected String convention;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String residueNumber;
    @XmlAttribute
    protected String title;
    @XmlAttribute
    protected String elementType;
    @XmlAttribute
    protected String id;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String customId;

    /**
     * Gets the value of the x2 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getX2() {
        return x2;
    }

    /**
     * Sets the value of the x2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setX2(Float value) {
        this.x2 = value;
    }

    /**
     * Gets the value of the x3 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getX3() {
        return x3;
    }

    /**
     * Sets the value of the x3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setX3(Float value) {
        this.x3 = value;
    }

    /**
     * Gets the value of the y2 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getY2() {
        return y2;
    }

    /**
     * Sets the value of the y2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setY2(Float value) {
        this.y2 = value;
    }

    /**
     * Gets the value of the y3 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getY3() {
        return y3;
    }

    /**
     * Sets the value of the y3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setY3(Float value) {
        this.y3 = value;
    }

    /**
     * Gets the value of the z3 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getZ3() {
        return z3;
    }

    /**
     * Sets the value of the z3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setZ3(Float value) {
        this.z3 = value;
    }

    /**
     * Gets the value of the residueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidueName() {
        return residueName;
    }

    /**
     * Sets the value of the residueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidueName(String value) {
        this.residueName = value;
    }

    /**
     * Gets the value of the atomName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtomName() {
        return atomName;
    }

    /**
     * Sets the value of the atomName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtomName(String value) {
        this.atomName = value;
    }

    /**
     * Gets the value of the chainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChainName() {
        return chainName;
    }

    /**
     * Sets the value of the chainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChainName(String value) {
        this.chainName = value;
    }

    /**
     * Gets the value of the dictRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDictRef() {
        return dictRef;
    }

    /**
     * Sets the value of the dictRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDictRef(String value) {
        this.dictRef = value;
    }

    /**
     * Gets the value of the formalCharge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFormalCharge() {
        return formalCharge;
    }

    /**
     * Sets the value of the formalCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFormalCharge(BigInteger value) {
        this.formalCharge = value;
    }

    /**
     * Gets the value of the vx property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVX() {
        return vx;
    }

    /**
     * Sets the value of the vx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVX(Double value) {
        this.vx = value;
    }

    /**
     * Gets the value of the vy property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVY() {
        return vy;
    }

    /**
     * Sets the value of the vy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVY(Double value) {
        this.vy = value;
    }

    /**
     * Gets the value of the vz property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVZ() {
        return vz;
    }

    /**
     * Sets the value of the vz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVZ(Double value) {
        this.vz = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCount(Double value) {
        this.count = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the altLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltLoc() {
        return altLoc;
    }

    /**
     * Sets the value of the altLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltLoc(String value) {
        this.altLoc = value;
    }

    /**
     * Gets the value of the convention property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConvention() {
        return convention;
    }

    /**
     * Sets the value of the convention property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConvention(String value) {
        this.convention = value;
    }

    /**
     * Gets the value of the residueNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidueNumber() {
        return residueNumber;
    }

    /**
     * Sets the value of the residueNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidueNumber(String value) {
        this.residueNumber = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the elementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementType() {
        return elementType;
    }

    /**
     * Sets the value of the elementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementType(String value) {
        this.elementType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the customId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomId() {
        return customId;
    }

    /**
     * Sets the value of the customId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomId(String value) {
        this.customId = value;
    }

}
