//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.27 at 11:01:57 AM CEST 
//


package de.mosgrid.msml.jaxb.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for moduleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="moduleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.xml-cml.org/schema/cmlx}parserConfiguration" minOccurs="0"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema/cmlx}adapterConfiguration" minOccurs="0"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema/cmlx}uploadList" minOccurs="0"/>
 *         &lt;element name="propertyList" type="{http://www.xml-cml.org/schema}propertyListType" minOccurs="0"/>
 *         &lt;element ref="{http://www.xml-cml.org/schema}molecule" minOccurs="0"/>
 *         &lt;element name="parameterList" type="{http://www.xml-cml.org/schema}parameterListType" minOccurs="0"/>
 *         &lt;element name="module" type="{http://www.xml-cml.org/schema}moduleType" minOccurs="0"/>
 *         &lt;element name="atomArray" type="{http://www.xml-cml.org/schema}atomArrayType" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.xml-cml.org/schema}descriptionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}workflowGraph"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}dictRef"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}workflowNotes"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}displayName"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}id"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}title"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "moduleType", propOrder = {
    "parserConfigurationAndAdapterConfigurationAndUploadList"
})
public class ModuleType {

    @XmlElements({
        @XmlElement(name = "module", type = ModuleType.class),
        @XmlElement(name = "molecule", type = MoleculeType.class),
        @XmlElement(name = "parameterList", type = ParameterListType.class),
        @XmlElement(name = "atomArray", type = AtomArrayType.class),
        @XmlElement(name = "uploadList", namespace = "http://www.xml-cml.org/schema/cmlx", type = UploadList.class),
        @XmlElement(name = "adapterConfiguration", namespace = "http://www.xml-cml.org/schema/cmlx", type = AdapterConfigType.class),
        @XmlElement(name = "description", type = DescriptionType.class),
        @XmlElement(name = "parserConfiguration", namespace = "http://www.xml-cml.org/schema/cmlx", type = ParserConfigType.class),
        @XmlElement(name = "propertyList", type = PropertyListType.class)
    })
    protected List<Object> parserConfigurationAndAdapterConfigurationAndUploadList;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String workflowGraph;
    @XmlAttribute
    protected String dictRef;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String workflowNotes;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String displayName;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String title;

    /**
     * Gets the value of the parserConfigurationAndAdapterConfigurationAndUploadList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parserConfigurationAndAdapterConfigurationAndUploadList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParserConfigurationAndAdapterConfigurationAndUploadList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModuleType }
     * {@link MoleculeType }
     * {@link ParameterListType }
     * {@link AtomArrayType }
     * {@link UploadList }
     * {@link AdapterConfigType }
     * {@link DescriptionType }
     * {@link ParserConfigType }
     * {@link PropertyListType }
     * 
     * 
     */
    public List<Object> getParserConfigurationAndAdapterConfigurationAndUploadList() {
        if (parserConfigurationAndAdapterConfigurationAndUploadList == null) {
            parserConfigurationAndAdapterConfigurationAndUploadList = new ArrayList<Object>();
        }
        return this.parserConfigurationAndAdapterConfigurationAndUploadList;
    }

    /**
     * Gets the value of the workflowGraph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowGraph() {
        return workflowGraph;
    }

    /**
     * Sets the value of the workflowGraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowGraph(String value) {
        this.workflowGraph = value;
    }

    /**
     * Gets the value of the dictRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDictRef() {
        return dictRef;
    }

    /**
     * Sets the value of the dictRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDictRef(String value) {
        this.dictRef = value;
    }

    /**
     * Gets the value of the workflowNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowNotes() {
        return workflowNotes;
    }

    /**
     * Sets the value of the workflowNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowNotes(String value) {
        this.workflowNotes = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

}
