//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.27 at 11:01:57 AM CEST 
//


package de.mosgrid.msml.jaxb.bindings;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for moleculeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="moleculeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.xml-cml.org/schema}molecule" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.xml-cml.org/schema/cmlx}customProperty" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;sequence>
 *             &lt;element name="atomArray" type="{http://www.xml-cml.org/schema}atomArrayType"/>
 *             &lt;element name="bondArray" type="{http://www.xml-cml.org/schema}bondArrayType" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}fileRef"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}process"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}dictRef"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}count"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}spinMultiplicity"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}formalCharge"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}id"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}origin"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}title"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}formula"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}chirality"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}customId"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}ref"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema/cmlx}moleculeClass"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}convention"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}symmetryOriented"/>
 *       &lt;attGroup ref="{http://www.xml-cml.org/schema}role"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "moleculeType", propOrder = {
    "molecule",
    "customProperty",
    "atomArray",
    "bondArray"
})
public class MoleculeType {

    protected List<MoleculeType> molecule;
    @XmlElement(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected List<CustomProperty> customProperty;
    protected AtomArrayType atomArray;
    protected BondArrayType bondArray;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String fileRef;
    @XmlAttribute
    protected String process;
    @XmlAttribute
    protected String dictRef;
    @XmlAttribute
    protected Double count;
    @XmlAttribute
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger spinMultiplicity;
    @XmlAttribute
    protected BigInteger formalCharge;
    @XmlAttribute
    protected String id;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected OriginType origin;
    @XmlAttribute
    protected String title;
    @XmlAttribute
    protected String formula;
    @XmlAttribute
    protected ChiralityType chirality;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected String customId;
    @XmlAttribute
    protected String ref;
    @XmlAttribute(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected MoleculeClassType moleculeClass;
    @XmlAttribute
    protected String convention;
    @XmlAttribute
    protected Boolean symmetryOriented;
    @XmlAttribute
    protected String role;

    /**
     * Gets the value of the molecule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the molecule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMolecule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MoleculeType }
     * 
     * 
     */
    public List<MoleculeType> getMolecule() {
        if (molecule == null) {
            molecule = new ArrayList<MoleculeType>();
        }
        return this.molecule;
    }

    /**
     * Gets the value of the customProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomProperty }
     * 
     * 
     */
    public List<CustomProperty> getCustomProperty() {
        if (customProperty == null) {
            customProperty = new ArrayList<CustomProperty>();
        }
        return this.customProperty;
    }

    /**
     * Gets the value of the atomArray property.
     * 
     * @return
     *     possible object is
     *     {@link AtomArrayType }
     *     
     */
    public AtomArrayType getAtomArray() {
        return atomArray;
    }

    /**
     * Sets the value of the atomArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtomArrayType }
     *     
     */
    public void setAtomArray(AtomArrayType value) {
        this.atomArray = value;
    }

    /**
     * Gets the value of the bondArray property.
     * 
     * @return
     *     possible object is
     *     {@link BondArrayType }
     *     
     */
    public BondArrayType getBondArray() {
        return bondArray;
    }

    /**
     * Sets the value of the bondArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link BondArrayType }
     *     
     */
    public void setBondArray(BondArrayType value) {
        this.bondArray = value;
    }

    /**
     * Gets the value of the fileRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileRef() {
        return fileRef;
    }

    /**
     * Sets the value of the fileRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileRef(String value) {
        this.fileRef = value;
    }

    /**
     * Gets the value of the process property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcess() {
        return process;
    }

    /**
     * Sets the value of the process property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcess(String value) {
        this.process = value;
    }

    /**
     * Gets the value of the dictRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDictRef() {
        return dictRef;
    }

    /**
     * Sets the value of the dictRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDictRef(String value) {
        this.dictRef = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCount(Double value) {
        this.count = value;
    }

    /**
     * Gets the value of the spinMultiplicity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpinMultiplicity() {
        return spinMultiplicity;
    }

    /**
     * Sets the value of the spinMultiplicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpinMultiplicity(BigInteger value) {
        this.spinMultiplicity = value;
    }

    /**
     * Gets the value of the formalCharge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFormalCharge() {
        return formalCharge;
    }

    /**
     * Sets the value of the formalCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFormalCharge(BigInteger value) {
        this.formalCharge = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link OriginType }
     *     
     */
    public OriginType getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginType }
     *     
     */
    public void setOrigin(OriginType value) {
        this.origin = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the formula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormula() {
        return formula;
    }

    /**
     * Sets the value of the formula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormula(String value) {
        this.formula = value;
    }

    /**
     * Gets the value of the chirality property.
     * 
     * @return
     *     possible object is
     *     {@link ChiralityType }
     *     
     */
    public ChiralityType getChirality() {
        return chirality;
    }

    /**
     * Sets the value of the chirality property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChiralityType }
     *     
     */
    public void setChirality(ChiralityType value) {
        this.chirality = value;
    }

    /**
     * Gets the value of the customId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomId() {
        return customId;
    }

    /**
     * Sets the value of the customId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomId(String value) {
        this.customId = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the moleculeClass property.
     * 
     * @return
     *     possible object is
     *     {@link MoleculeClassType }
     *     
     */
    public MoleculeClassType getMoleculeClass() {
        return moleculeClass;
    }

    /**
     * Sets the value of the moleculeClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoleculeClassType }
     *     
     */
    public void setMoleculeClass(MoleculeClassType value) {
        this.moleculeClass = value;
    }

    /**
     * Gets the value of the convention property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConvention() {
        return convention;
    }

    /**
     * Sets the value of the convention property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConvention(String value) {
        this.convention = value;
    }

    /**
     * Gets the value of the symmetryOriented property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSymmetryOriented() {
        return symmetryOriented;
    }

    /**
     * Sets the value of the symmetryOriented property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSymmetryOriented(Boolean value) {
        this.symmetryOriented = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
