//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.27 at 11:01:57 AM CEST 
//


package de.mosgrid.msml.jaxb.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for adapterConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adapterConfigType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xml-cml.org/schema}parameterListType">
 *       &lt;attribute name="adapterID" use="required" type="{http://www.xml-cml.org/schema}namespaceRefType" />
 *       &lt;attribute name="portName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fileExtension">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[^\.]\w*"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adapterConfigType", namespace = "http://www.xml-cml.org/schema/cmlx")
public class AdapterConfigType
    extends ParameterListType
{

    @XmlAttribute(required = true)
    protected String adapterID;
    @XmlAttribute
    protected String portName;
    @XmlAttribute
    protected String fileExtension;

    /**
     * Gets the value of the adapterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdapterID() {
        return adapterID;
    }

    /**
     * Sets the value of the adapterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdapterID(String value) {
        this.adapterID = value;
    }

    /**
     * Gets the value of the portName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortName() {
        return portName;
    }

    /**
     * Sets the value of the portName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortName(String value) {
        this.portName = value;
    }

    /**
     * Gets the value of the fileExtension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileExtension() {
        return fileExtension;
    }

    /**
     * Sets the value of the fileExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileExtension(String value) {
        this.fileExtension = value;
    }

}
