//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.27 at 11:01:57 AM CEST 
//


package de.mosgrid.msml.jaxb.bindings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for moleculeClassType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="moleculeClassType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Model"/>
 *     &lt;enumeration value="Chain"/>
 *     &lt;enumeration value="AminoAcid"/>
 *     &lt;enumeration value="Nucleotide"/>
 *     &lt;enumeration value="Hetero"/>
 *     &lt;enumeration value="MoleculeList"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "moleculeClassType", namespace = "http://www.xml-cml.org/schema/cmlx")
@XmlEnum
public enum MoleculeClassType {

    @XmlEnumValue("Model")
    MODEL("Model"),
    @XmlEnumValue("Chain")
    CHAIN("Chain"),
    @XmlEnumValue("AminoAcid")
    AMINO_ACID("AminoAcid"),
    @XmlEnumValue("Nucleotide")
    NUCLEOTIDE("Nucleotide"),
    @XmlEnumValue("Hetero")
    HETERO("Hetero"),
    @XmlEnumValue("MoleculeList")
    MOLECULE_LIST("MoleculeList");
    private final String value;

    MoleculeClassType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MoleculeClassType fromValue(String v) {
        for (MoleculeClassType c: MoleculeClassType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
