//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.27 at 11:01:57 AM CEST 
//


package de.mosgrid.msml.jaxb.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.mosgrid.msml.jaxb.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ParserConfiguration_QNAME = new QName("http://www.xml-cml.org/schema/cmlx", "parserConfiguration");
    private final static QName _Molecule_QNAME = new QName("http://www.xml-cml.org/schema", "molecule");
    private final static QName _AdapterConfiguration_QNAME = new QName("http://www.xml-cml.org/schema/cmlx", "adapterConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.mosgrid.msml.jaxb.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Restriction }
     * 
     */
    public Restriction createRestriction() {
        return new Restriction();
    }

    /**
     * Create an instance of {@link MoleculeUploadType }
     * 
     */
    public MoleculeUploadType createMoleculeUploadType() {
        return new MoleculeUploadType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link BondArrayType }
     * 
     */
    public BondArrayType createBondArrayType() {
        return new BondArrayType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link ParameterListType }
     * 
     */
    public ParameterListType createParameterListType() {
        return new ParameterListType();
    }

    /**
     * Create an instance of {@link DefinitionType }
     * 
     */
    public DefinitionType createDefinitionType() {
        return new DefinitionType();
    }

    /**
     * Create an instance of {@link Dictionary }
     * 
     */
    public Dictionary createDictionary() {
        return new Dictionary();
    }

    /**
     * Create an instance of {@link ModuleType }
     * 
     */
    public ModuleType createModuleType() {
        return new ModuleType();
    }

    /**
     * Create an instance of {@link BondType }
     * 
     */
    public BondType createBondType() {
        return new BondType();
    }

    /**
     * Create an instance of {@link MoleculeType }
     * 
     */
    public MoleculeType createMoleculeType() {
        return new MoleculeType();
    }

    /**
     * Create an instance of {@link MatrixType }
     * 
     */
    public MatrixType createMatrixType() {
        return new MatrixType();
    }

    /**
     * Create an instance of {@link ScalarType }
     * 
     */
    public ScalarType createScalarType() {
        return new ScalarType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link AtomType }
     * 
     */
    public AtomType createAtomType() {
        return new AtomType();
    }

    /**
     * Create an instance of {@link ArrayType }
     * 
     */
    public ArrayType createArrayType() {
        return new ArrayType();
    }

    /**
     * Create an instance of {@link CustomProperty }
     * 
     */
    public CustomProperty createCustomProperty() {
        return new CustomProperty();
    }

    /**
     * Create an instance of {@link AtomArrayType }
     * 
     */
    public AtomArrayType createAtomArrayType() {
        return new AtomArrayType();
    }

    /**
     * Create an instance of {@link ParserConfigType }
     * 
     */
    public ParserConfigType createParserConfigType() {
        return new ParserConfigType();
    }

    /**
     * Create an instance of {@link FileUpload }
     * 
     */
    public FileUpload createFileUpload() {
        return new FileUpload();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link UploadList }
     * 
     */
    public UploadList createUploadList() {
        return new UploadList();
    }

    /**
     * Create an instance of {@link JobInputUploadType }
     * 
     */
    public JobInputUploadType createJobInputUploadType() {
        return new JobInputUploadType();
    }

    /**
     * Create an instance of {@link AdapterConfigType }
     * 
     */
    public AdapterConfigType createAdapterConfigType() {
        return new AdapterConfigType();
    }

    /**
     * Create an instance of {@link PropertyListType }
     * 
     */
    public PropertyListType createPropertyListType() {
        return new PropertyListType();
    }

    /**
     * Create an instance of {@link Cml }
     * 
     */
    public Cml createCml() {
        return new Cml();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParserConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml-cml.org/schema/cmlx", name = "parserConfiguration")
    public JAXBElement<ParserConfigType> createParserConfiguration(ParserConfigType value) {
        return new JAXBElement<ParserConfigType>(_ParserConfiguration_QNAME, ParserConfigType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MoleculeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml-cml.org/schema", name = "molecule")
    public JAXBElement<MoleculeType> createMolecule(MoleculeType value) {
        return new JAXBElement<MoleculeType>(_Molecule_QNAME, MoleculeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdapterConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xml-cml.org/schema/cmlx", name = "adapterConfiguration")
    public JAXBElement<AdapterConfigType> createAdapterConfiguration(AdapterConfigType value) {
        return new JAXBElement<AdapterConfigType>(_AdapterConfiguration_QNAME, AdapterConfigType.class, null, value);
    }

}
