//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.27 at 11:01:57 AM CEST 
//


package de.mosgrid.msml.jaxb.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="moleculeUpload" type="{http://www.xml-cml.org/schema/cmlx}moleculeUploadType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="jobInputUpload" type="{http://www.xml-cml.org/schema/cmlx}jobInputUploadType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "moleculeUpload",
    "jobInputUpload"
})
@XmlRootElement(name = "uploadList", namespace = "http://www.xml-cml.org/schema/cmlx")
public class UploadList {

    @XmlElement(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected List<MoleculeUploadType> moleculeUpload;
    @XmlElement(namespace = "http://www.xml-cml.org/schema/cmlx")
    protected List<JobInputUploadType> jobInputUpload;

    /**
     * Gets the value of the moleculeUpload property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moleculeUpload property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMoleculeUpload().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MoleculeUploadType }
     * 
     * 
     */
    public List<MoleculeUploadType> getMoleculeUpload() {
        if (moleculeUpload == null) {
            moleculeUpload = new ArrayList<MoleculeUploadType>();
        }
        return this.moleculeUpload;
    }

    /**
     * Gets the value of the jobInputUpload property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobInputUpload property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobInputUpload().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobInputUploadType }
     * 
     * 
     */
    public List<JobInputUploadType> getJobInputUpload() {
        if (jobInputUpload == null) {
            jobInputUpload = new ArrayList<JobInputUploadType>();
        }
        return this.jobInputUpload;
    }

}
