//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.17 at 02:32:49 PM CEST 
//


package de.ukoeln.msml.genericparser.gui.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigRootType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigRootType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="simpl" type="{http://www.mosgrid.de/genericparser}ConfigSimplType"/>
 *         &lt;element name="adv" type="{http://www.mosgrid.de/genericparser}ConfigAdvType"/>
 *         &lt;element name="dicts" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigRootType", propOrder = {
    "simpl",
    "adv",
    "dicts"
})
public class ConfigRootType {

    @XmlElement(required = true)
    protected ConfigSimplType simpl;
    @XmlElement(required = true)
    protected ConfigAdvType adv;
    protected List<String> dicts;

    /**
     * Gets the value of the simpl property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigSimplType }
     *     
     */
    public ConfigSimplType getSimpl() {
        return simpl;
    }

    /**
     * Sets the value of the simpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigSimplType }
     *     
     */
    public void setSimpl(ConfigSimplType value) {
        this.simpl = value;
    }

    /**
     * Gets the value of the adv property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigAdvType }
     *     
     */
    public ConfigAdvType getAdv() {
        return adv;
    }

    /**
     * Sets the value of the adv property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigAdvType }
     *     
     */
    public void setAdv(ConfigAdvType value) {
        this.adv = value;
    }

    /**
     * Gets the value of the dicts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dicts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDicts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDicts() {
        if (dicts == null) {
            dicts = new ArrayList<String>();
        }
        return this.dicts;
    }

}
