//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.17 at 02:32:49 PM CEST 
//


package de.ukoeln.msml.genericparser.gui.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LayerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="layerConfig" type="{http://www.mosgrid.de/genericparser}GenericParserExtensionConfig" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="separatorPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="newSeparator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayerType", propOrder = {
    "layerConfig"
})
public class LayerType {

    protected List<GenericParserExtensionConfig> layerConfig;
    @XmlAttribute
    protected String separatorPattern;
    @XmlAttribute
    protected String newSeparator;

    /**
     * Gets the value of the layerConfig property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layerConfig property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayerConfig().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericParserExtensionConfig }
     * 
     * 
     */
    public List<GenericParserExtensionConfig> getLayerConfig() {
        if (layerConfig == null) {
            layerConfig = new ArrayList<GenericParserExtensionConfig>();
        }
        return this.layerConfig;
    }

    /**
     * Gets the value of the separatorPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparatorPattern() {
        return separatorPattern;
    }

    /**
     * Sets the value of the separatorPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparatorPattern(String value) {
        this.separatorPattern = value;
    }

    /**
     * Gets the value of the newSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewSeparator() {
        return newSeparator;
    }

    /**
     * Sets the value of the newSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewSeparator(String value) {
        this.newSeparator = value;
    }

}
