//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.17 at 02:32:49 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mosgrid.de/genericparser", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.ukoeln.msml.genericparser.gui.configuration;
