package de.mosgrid.ukoeln.templatedesigner.gui.templatetab;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.AbstractLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;

import de.mosgrid.ukoeln.templatedesigner.document.TDTemplateDocument;
import de.mosgrid.ukoeln.templatedesigner.gui.TDCloseListener;
import de.mosgrid.ukoeln.templatedesigner.gui.TDViewBase;

public class TDTemplateTab extends TDViewBase<TDTemplateDocument> implements TDCloseListener {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Panel pnlViews;
	@AutoGenerated
	private VerticalLayout vlViews;
	@AutoGenerated
	private VerticalLayout vlJobsButtons;
	@AutoGenerated
	private Button btnSave;
	@AutoGenerated
	private HorizontalLayout hlButtons;
	@AutoGenerated
	private Button btnRemove;
	@AutoGenerated
	private Button btnAdd;
	@AutoGenerated
	private ComboBox cmbUnassignedJobs;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Tree treJobs;
	
	private static final long serialVersionUID = -1611489279247600686L;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public TDTemplateTab() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		setSizeFull();
		setImmediate(true);
	}

	public TDTemplateTab(String caption) {
		this();
		setCaption(caption);
	}

	@Override
	public AbstractLayout getMainLayout() {
		return mainLayout;
	}

	@Override
	protected void doInit() {
		btnSave.addListener(new ClickListener() {
			
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				getDoc().saveAndReloadComplete();
			}
		});
		
		btnRemove.setEnabled(false);
		btnRemove.addListener(new ClickListener() {
			
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				getDoc().removeJob((TDTemplateViewJob)treJobs.getValue(), true);
			}
		});
		
		btnAdd.setEnabled(false);
		btnAdd.addListener(new ClickListener() {

			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				getDoc().addJob((String) cmbUnassignedJobs.getValue());
				treJobs.select(null);
			}
		});
		
		cmbUnassignedJobs.setContainerDataSource(getDoc().getUnassignedJobsDataSource());		
		cmbUnassignedJobs.addListener(new ValueChangeListener() {

			private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				btnAdd.setEnabled(cmbUnassignedJobs.getValue() != null);
			}
		});
		
		treJobs.setContainerDataSource(getDoc().getViews());
		treJobs.addListener(new ValueChangeListener() {

			private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				pnlViews.removeAllComponents();
				if (treJobs.getValue() != null)
					pnlViews.addComponent((Component) treJobs.getValue());
				updateRemoveButton();
			}
		});
		getDoc().updateUnassignedJobs();
	}

	private void updateRemoveButton() {
		btnRemove.setEnabled(treJobs.getValue() != null && treJobs.getValue() instanceof TDTemplateViewJob);
	}

	public void updateUnassignedJobs() {
		BeanItemContainer<String> uJobs = getDoc().getUnassignedJobsDataSource();
		boolean jobs = uJobs.size() != 0;
		cmbUnassignedJobs.setEnabled(jobs);
		cmbUnassignedJobs.setNullSelectionAllowed(!jobs);
		if (!jobs) {
			cmbUnassignedJobs.setValue(null);
		}
	}

	public void selectJob(TDTemplateViewJob newview) {
		treJobs.select(newview);
		treJobs.requestRepaint();
	}

	@Override
	public void onClose() {
		getDoc().onClose();
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// vlJobsButtons
		vlJobsButtons = buildVlJobsButtons();
		mainLayout.addComponent(vlJobsButtons);
		mainLayout.setExpandRatio(vlJobsButtons, 0.2f);
		
		// pnlViews
		pnlViews = buildPnlViews();
		mainLayout.addComponent(pnlViews);
		mainLayout.setExpandRatio(pnlViews, 0.7f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVlJobsButtons() {
		// common part: create layout
		vlJobsButtons = new VerticalLayout();
		vlJobsButtons.setImmediate(false);
		vlJobsButtons.setWidth("100.0%");
		vlJobsButtons.setHeight("100.0%");
		vlJobsButtons.setMargin(false);
		vlJobsButtons.setSpacing(true);
		
		// panel_1
		panel_1 = buildPanel_1();
		vlJobsButtons.addComponent(panel_1);
		vlJobsButtons.setExpandRatio(panel_1, 0.7f);
		
		// cmbUnassignedJobs
		cmbUnassignedJobs = new ComboBox();
		cmbUnassignedJobs.setCaption("Unassigned Jobs");
		cmbUnassignedJobs.setImmediate(true);
		cmbUnassignedJobs.setWidth("100.0%");
		cmbUnassignedJobs.setHeight("-1px");
		vlJobsButtons.addComponent(cmbUnassignedJobs);
		
		// hlButtons
		hlButtons = buildHlButtons();
		vlJobsButtons.addComponent(hlButtons);
		
		// btnSave
		btnSave = new Button();
		btnSave.setCaption("Save");
		btnSave.setImmediate(true);
		btnSave.setWidth("100.0%");
		btnSave.setHeight("-1px");
		vlJobsButtons.addComponent(btnSave);
		
		return vlJobsButtons;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		panel_1.setContent(verticalLayout_1);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(false);
		
		// treJobs
		treJobs = new Tree();
		treJobs.setCaption("Main Info / Jobs");
		treJobs.setImmediate(true);
		treJobs.setWidth("-1px");
		treJobs.setHeight("-1px");
		verticalLayout_1.addComponent(treJobs);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHlButtons() {
		// common part: create layout
		hlButtons = new HorizontalLayout();
		hlButtons.setImmediate(false);
		hlButtons.setWidth("100.0%");
		hlButtons.setHeight("-1px");
		hlButtons.setMargin(false);
		hlButtons.setSpacing(true);
		
		// btnAdd
		btnAdd = new Button();
		btnAdd.setCaption("Add");
		btnAdd.setImmediate(true);
		btnAdd.setWidth("100.0%");
		btnAdd.setHeight("-1px");
		hlButtons.addComponent(btnAdd);
		
		// btnRemove
		btnRemove = new Button();
		btnRemove.setCaption("Remove");
		btnRemove.setImmediate(true);
		btnRemove.setWidth("100.0%");
		btnRemove.setHeight("-1px");
		hlButtons.addComponent(btnRemove);
		
		return hlButtons;
	}

	@AutoGenerated
	private Panel buildPnlViews() {
		// common part: create layout
		pnlViews = new Panel();
		pnlViews.setImmediate(false);
		pnlViews.setWidth("100.0%");
		pnlViews.setHeight("100.0%");
		
		// vlViews
		vlViews = new VerticalLayout();
		vlViews.setImmediate(false);
		vlViews.setWidth("100.0%");
		vlViews.setHeight("100.0%");
		vlViews.setMargin(false);
		pnlViews.setContent(vlViews);
		
		return pnlViews;
	}
}
