//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.17 at 02:32:49 PM CEST 
//


package de.ukoeln.msml.genericparser.gui.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.ukoeln.msml.genericparser.gui.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Root_QNAME = new QName("http://www.mosgrid.de/genericparser", "root");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.ukoeln.msml.genericparser.gui.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigSimplType }
     * 
     */
    public ConfigSimplType createConfigSimplType() {
        return new ConfigSimplType();
    }

    /**
     * Create an instance of {@link GenericParserConfig }
     * 
     */
    public GenericParserConfig createGenericParserConfig() {
        return new GenericParserConfig();
    }

    /**
     * Create an instance of {@link LayerType }
     * 
     */
    public LayerType createLayerType() {
        return new LayerType();
    }

    /**
     * Create an instance of {@link GenericParserExtensionConfigEntry }
     * 
     */
    public GenericParserExtensionConfigEntry createGenericParserExtensionConfigEntry() {
        return new GenericParserExtensionConfigEntry();
    }

    /**
     * Create an instance of {@link GenericParserExtensionConfig }
     * 
     */
    public GenericParserExtensionConfig createGenericParserExtensionConfig() {
        return new GenericParserExtensionConfig();
    }

    /**
     * Create an instance of {@link ConfigRootType }
     * 
     */
    public ConfigRootType createConfigRootType() {
        return new ConfigRootType();
    }

    /**
     * Create an instance of {@link ConfigAdvType }
     * 
     */
    public ConfigAdvType createConfigAdvType() {
        return new ConfigAdvType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigRootType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mosgrid.de/genericparser", name = "root")
    public JAXBElement<ConfigRootType> createRoot(ConfigRootType value) {
        return new JAXBElement<ConfigRootType>(_Root_QNAME, ConfigRootType.class, null, value);
    }

}
